apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configmap
data:
  SERVICE_TO_RUN: "web"
---
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: app
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  minReadySeconds: 10
  replicas: 1
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image:
          envFrom:
            - configMapRef:
                name: app-configmap
          resources:
            limits:
              cpu: 150m
              memory: 300Mi
